/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladores.ControladorModulos;
import Dao.DaoInfo;
import Dao.IDaoInfo;
import Modelos.InfoPanel;

/**
 *
 * @author poseidon
 */
public class Vistaaprendizaje extends javax.swing.JFrame {

    /**
     * Creates new form Vistaaprendizaje
     */
    public Vistaaprendizaje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        entornoDesarrollo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        condiIf = new javax.swing.JButton();
        introduccion = new javax.swing.JButton();
        condicionales = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        estructuraDatos = new javax.swing.JButton();
        tipoDatos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        variables = new javax.swing.JButton();
        constantes = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        entrDatos = new javax.swing.JButton();
        daliDatos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtNombre.setText("jLabel1");
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 100, 280, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Entornos de desarrollo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 170, 30));

        entornoDesarrollo.setBackground(new java.awt.Color(255, 51, 51));
        entornoDesarrollo.setText("Ver");
        entornoDesarrollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entornoDesarrolloActionPerformed(evt);
            }
        });
        jPanel1.add(entornoDesarrollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 80, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Condicionales");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 170, 30));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("< Volver");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jLabel4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel4KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 70, 30));

        condiIf.setBackground(new java.awt.Color(255, 51, 51));
        condiIf.setText("Condicional If");
        condiIf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                condiIfActionPerformed(evt);
            }
        });
        jPanel1.add(condiIf, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, 150, 30));

        introduccion.setBackground(new java.awt.Color(255, 51, 51));
        introduccion.setText("Ver");
        introduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introduccionActionPerformed(evt);
            }
        });
        jPanel1.add(introduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 80, 30));

        condicionales.setBackground(new java.awt.Color(255, 51, 51));
        condicionales.setText("¿Qué son?");
        condicionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                condicionalesActionPerformed(evt);
            }
        });
        jPanel1.add(condicionales, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, 140, 30));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Datos en C++");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 170, 30));

        estructuraDatos.setBackground(new java.awt.Color(255, 51, 51));
        estructuraDatos.setText("Estructura de datos");
        estructuraDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estructuraDatosActionPerformed(evt);
            }
        });
        jPanel1.add(estructuraDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 140, 30));

        tipoDatos.setBackground(new java.awt.Color(255, 51, 51));
        tipoDatos.setText("Tipo de datos");
        tipoDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoDatosActionPerformed(evt);
            }
        });
        jPanel1.add(tipoDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 150, 30));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Variables y constantes");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 170, 30));

        variables.setBackground(new java.awt.Color(255, 51, 51));
        variables.setText("Variables");
        variables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                variablesActionPerformed(evt);
            }
        });
        jPanel1.add(variables, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 140, 30));

        constantes.setBackground(new java.awt.Color(255, 51, 51));
        constantes.setText("Constantes");
        constantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                constantesActionPerformed(evt);
            }
        });
        jPanel1.add(constantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 150, 30));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Entreda y salida de datos");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 170, 30));

        entrDatos.setBackground(new java.awt.Color(255, 51, 51));
        entrDatos.setText("Entrada de datos");
        entrDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrDatosActionPerformed(evt);
            }
        });
        jPanel1.add(entrDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 140, 30));

        daliDatos.setBackground(new java.awt.Color(255, 51, 51));
        daliDatos.setText("Salida de datos");
        daliDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daliDatosActionPerformed(evt);
            }
        });
        jPanel1.add(daliDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 150, 30));

        txtInfo.setEditable(false);
        txtInfo.setBackground(new java.awt.Color(255, 255, 255));
        txtInfo.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(txtInfo);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 640, 500));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Introducción");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 196, 170, 30));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Elija la temática que quisiera aprender y en el sigyiente panel se le mostrará la información");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 600, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/emergente.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entornoDesarrolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entornoDesarrolloActionPerformed
        // TODO add your handling code here:
        setDatos(2);
    }//GEN-LAST:event_entornoDesarrolloActionPerformed

    private void introduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introduccionActionPerformed
        // TODO add your handling code here:
        setDatos(1);
    }//GEN-LAST:event_introduccionActionPerformed

    private void condiIfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_condiIfActionPerformed
        // TODO add your handling code here:
        setDatos(10);
    }//GEN-LAST:event_condiIfActionPerformed

    private void condicionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_condicionalesActionPerformed
        // TODO add your handling code here:
        setDatos(9);
    }//GEN-LAST:event_condicionalesActionPerformed

    private void estructuraDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estructuraDatosActionPerformed
        // TODO add your handling code here:
        setDatos(3);
    }//GEN-LAST:event_estructuraDatosActionPerformed

    private void tipoDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDatosActionPerformed
        // TODO add your handling code here:
        setDatos(4);
    }//GEN-LAST:event_tipoDatosActionPerformed

    private void variablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variablesActionPerformed
        // TODO add your handling code here:
        setDatos(5);
    }//GEN-LAST:event_variablesActionPerformed

    private void constantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_constantesActionPerformed
        // TODO add your handling code here:
        setDatos(6);
    }//GEN-LAST:event_constantesActionPerformed

    private void entrDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrDatosActionPerformed
        // TODO add your handling code here:
        setDatos(7);
    }//GEN-LAST:event_entrDatosActionPerformed

    private void daliDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daliDatosActionPerformed
        // TODO add your handling code here:
        setDatos(8);
    }//GEN-LAST:event_daliDatosActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        dispose();
        ControladorModulos.inicio(txtNombre.getText());
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4KeyPressed

    public void setDatos(int id){
        IDaoInfo iDaoInfo = new DaoInfo();
        for(InfoPanel info : iDaoInfo.verInfo()){
            if(info.getIdInfo() == id){
                txtInfo.setText(info.getTitulo().toUpperCase() + "\n\n" + info.getCuerpo());
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vistaaprendizaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vistaaprendizaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vistaaprendizaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vistaaprendizaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vistaaprendizaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton condiIf;
    private javax.swing.JButton condicionales;
    private javax.swing.JButton constantes;
    private javax.swing.JButton daliDatos;
    private javax.swing.JButton entornoDesarrollo;
    private javax.swing.JButton entrDatos;
    private javax.swing.JButton estructuraDatos;
    private javax.swing.JButton introduccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton tipoDatos;
    private javax.swing.JTextPane txtInfo;
    public javax.swing.JLabel txtNombre;
    private javax.swing.JButton variables;
    // End of variables declaration//GEN-END:variables
}
